name: GitHub Actions Demo
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8, 3.9]
    steps:
      - run: echo "Job started!"
      - name: Install dependencies
        run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
      - run: echo "This job's status is ${{ job.status }}."
